/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.futurecollars.invoicing;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import pl.futurecollars.invoicing.db.Database;
import pl.futurecollars.invoicing.db.memory.InMemoryDatabase;
import pl.futurecollars.invoicing.model.Company;
import pl.futurecollars.invoicing.model.Invoice;
import pl.futurecollars.invoicing.model.InvoiceEntry;
import pl.futurecollars.invoicing.model.Vat;
import pl.futurecollars.invoicing.service.InvoiceService;

public class App {
  static Database database = new InMemoryDatabase();

  public static void main(String[] args) {

    InvoiceService invoiceService = new InvoiceService(database);

    Company firstCompany = new Company(1, "Company#1", "Warsaw, Poleska 5");
    Company secondCompany = new Company(2, "Company#2", "Warsaw, Poleska 6");

    InvoiceEntry firstEntry = new InvoiceEntry("Some service", new BigDecimal(200), new BigDecimal(2), Vat.Vat_23);

    Invoice invoice = Invoice.builder()
        .date(LocalDate.now())
        .fromCompany(firstCompany)
        .toCompany(secondCompany)
        .invoiceEntries(List.of(firstEntry))
        .build();

    long id = invoiceService.saveInvoice(invoice);
    System.out.println(invoiceService.getInvoice(id));
  }
}
